//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NewMedusaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NewMedusaEntities object using the connection string found in the 'NewMedusaEntities' section of the application configuration file.
        /// </summary>
        public NewMedusaEntities() : base("name=NewMedusaEntities", "NewMedusaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewMedusaEntities object.
        /// </summary>
        public NewMedusaEntities(string connectionString) : base(connectionString, "NewMedusaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewMedusaEntities object.
        /// </summary>
        public NewMedusaEntities(EntityConnection connection) : base(connection, "NewMedusaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vContratosPessoa> vContratosPessoa
        {
            get
            {
                if ((_vContratosPessoa == null))
                {
                    _vContratosPessoa = base.CreateObjectSet<vContratosPessoa>("vContratosPessoa");
                }
                return _vContratosPessoa;
            }
        }
        private ObjectSet<vContratosPessoa> _vContratosPessoa;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vContratosPessoa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovContratosPessoa(vContratosPessoa vContratosPessoa)
        {
            base.AddObject("vContratosPessoa", vContratosPessoa);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MedusaModel1", Name="vContratosPessoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vContratosPessoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vContratosPessoa object.
        /// </summary>
        /// <param name="id_contrato">Initial value of the id_contrato property.</param>
        /// <param name="cpf">Initial value of the cpf property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        public static vContratosPessoa CreatevContratosPessoa(global::System.Int64 id_contrato, global::System.String cpf, global::System.String tipo)
        {
            vContratosPessoa vContratosPessoa = new vContratosPessoa();
            vContratosPessoa.id_contrato = id_contrato;
            vContratosPessoa.cpf = cpf;
            vContratosPessoa.tipo = tipo;
            return vContratosPessoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_contrato
        {
            get
            {
                return _id_contrato;
            }
            set
            {
                if (_id_contrato != value)
                {
                    Onid_contratoChanging(value);
                    ReportPropertyChanging("id_contrato");
                    _id_contrato = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_contrato");
                    Onid_contratoChanged();
                }
            }
        }
        private global::System.Int64 _id_contrato;
        partial void Onid_contratoChanging(global::System.Int64 value);
        partial void Onid_contratoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cpf
        {
            get
            {
                return _cpf;
            }
            set
            {
                OncpfChanging(value);
                ReportPropertyChanging("cpf");
                _cpf = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cpf");
                OncpfChanged();
            }
        }
        private global::System.String _cpf;
        partial void OncpfChanging(global::System.String value);
        partial void OncpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rg
        {
            get
            {
                return _rg;
            }
            set
            {
                OnrgChanging(value);
                ReportPropertyChanging("rg");
                _rg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rg");
                OnrgChanged();
            }
        }
        private global::System.String _rg;
        partial void OnrgChanging(global::System.String value);
        partial void OnrgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> projeto
        {
            get
            {
                return _projeto;
            }
            set
            {
                OnprojetoChanging(value);
                ReportPropertyChanging("projeto");
                _projeto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("projeto");
                OnprojetoChanged();
            }
        }
        private Nullable<global::System.Int32> _projeto;
        partial void OnprojetoChanging(Nullable<global::System.Int32> value);
        partial void OnprojetoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Decimal> _valor;
        partial void OnvalorChanging(Nullable<global::System.Decimal> value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> inicio
        {
            get
            {
                return _inicio;
            }
            set
            {
                OninicioChanging(value);
                ReportPropertyChanging("inicio");
                _inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inicio");
                OninicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _inicio;
        partial void OninicioChanging(Nullable<global::System.DateTime> value);
        partial void OninicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> termino
        {
            get
            {
                return _termino;
            }
            set
            {
                OnterminoChanging(value);
                ReportPropertyChanging("termino");
                _termino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("termino");
                OnterminoChanged();
            }
        }
        private Nullable<global::System.DateTime> _termino;
        partial void OnterminoChanging(Nullable<global::System.DateTime> value);
        partial void OnterminoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String obs
        {
            get
            {
                return _obs;
            }
            set
            {
                OnobsChanging(value);
                ReportPropertyChanging("obs");
                _obs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("obs");
                OnobsChanged();
            }
        }
        private global::System.String _obs;
        partial void OnobsChanging(global::System.String value);
        partial void OnobsChanged();

        #endregion
    
    }

    #endregion
    
}
